[options]
db_host = 103.20.144.71
db_port = 5432
db_user = odoo
db_password = wuxHjuEAZvFa
db_name = odoo
admin_passwd = 123456
addons_path = /mnt/customaddons,/mnt/extra-addons
limit_memory_hard = 20737418240
limit_memory_soft = 16449239756
limit_request = 8192
limit_time_cpu = 11000
limit_time_real = 11000
limit_time_real_cron = -1
max_cron_threads = 3
workers = 0
db_maxconn = 64
max_connections = 100
longpolling_port = 8072
proxy_mode = True
log_level = debug